### ISSUE TITLE
Sett opp search.portalen.t-fk.no

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-arbeidsoppgaver#1]
Sett opp instans av https://github.com/telemark/tfk.search.service på adressen search.portalen.t-fk.no

**Comment by maccyber** [comment]
Satt opp på https://search.portalen.t-fk.no/
OBS. kommenterte ut ports for elasticserver, men ser ut til å fungere

```
elasticserver:
  image: elasticsearch:2.2.1
#  ports:
#     - "9200:9200"
#     - "9300:9300"
```
